#!/bin/sh
set -ue

flush_opcode=`config-get flush-opcode-cache`

if [ "$flush_opcode" = "True" ]; then
  juju-log "Flushing OpCode"
  curl "http://localhost:8080/sites/all/libraries/apc/apc.php?CC=1" > /dev/null
fi

