#!/bin/sh

set -ue
rm -f /etc/default/s3cmd
flush_opcode=`config-get flush-opcode-cache`

if [ "$flush_opcode" = "True" ]; then
  juju-log "Flushing OpCode"
  curl "http://localhost:8080/sites/all/libraries/apc/apc.php?CC=1" > /dev/null
fi

aws_access_key=`config-get aws-public-key`
aws_secret_key=`config-get aws-secret-key`

[ -n "$aws_access_key" ] || exit 0
[ -n "$aws_secret_key" ] || exit 0

rsync files/s3cmd /etc/default/

sed -i -e "s@access_key =.*@access_key = $aws_access_key@" \
    -e "s@secret_key =.*@secret_key = $aws_secret_key@" \
    /etc/default/s3cmd
