#!/bin/bash

set -eu

juju-log "We've got a db"
hostname=`unit-get public-address`
private_name=`hostname -f`
juju-log "Retrieved hostname: $hostname"

# Check we haven't already been setup.
drupal_install_path="/var/www/drupal"
config_file_path="$drupal_install_path/sites/default/settings.php"

if [ -f "$config_file_path" ]; then
  juju-log "Drupal is already setup, just silently going away"
  exit 0
fi

database=`relation-get database`
user=`relation-get user`
password=`relation-get password`
host=`relation-get private-address`

if [ -z "$database" ] ; then
    exit 0
fi

# not used just yet, future enhancement
secret_key=`pwgen 10 1`
source "/usr/share/charm-helper/sh/net.sh"

juju-log "Grabbing the latest stable Drupal"
git clone -o pressflow git://github.com/pressflow/6.git /var/www/drupal

juju-log "Dropping Custom Drupal Themes, Modules, Libraries, etc in to position"
rsync -az files/drupal/ $drupal_install_path

juju-log "Writing Drupal config file $config_file_path"
# Write the Drupal config
cat > $config_file_path <<EOF
<?php
\$obstart = function ()
{
  if (extension_loaded('gzip')) {
    if (!ob_start('ob_gzhandler')) {
      ob_start();
    }
  } else {
    ob_start();
  }
};

if (!defined('DRUPAL_ROOT')) {
  define('DRUPAL_ROOT', getcwd());
}

global \$conf, \$db_url, \$drupal_db, \$cookie_domain, \$update_free_access, \$db_prefix;
error_reporting(E_ALL ^ (E_NOTICE | E_WARNING));

include_once(DRUPAL_ROOT . '/sites/all/libraries/Pixeldrop/ClassLoader/Loader.php');

\$update_free_access = false;
\$cookie_domain = \$_SERVER['HTTP_HOST'];
\$conf['pressflow_smart_start'] = true;

ini_set('zend.enable_gc', 0);
ini_set('display_errors', 0);
ini_set('timezone.default', 'UTC');
ini_set('date.timezone', 'UTC');
ini_set('realpath_cache_size', '64m');
ini_set('realpath_cache_ttl', '1800');
ini_set('arg_separator.output', '&amp;');
ini_set('magic_quotes_runtime', 0);
ini_set('magic_quotes_sybase', 0);
ini_set('session.cache_expire', 200000);
ini_set('session.cache_limiter', 'none');
ini_set('session.cookie_lifetime', 2000000);
ini_set('session.gc_maxlifetime', 200000);
ini_set('session.save_handler', 'user');
ini_set('session.use_cookies', 1);
ini_set('session.use_only_cookies', 1);
ini_set('session.use_trans_sid', 0);
ini_set('url_rewriter.tags', '');

//\$conf['cache_inc'] = 'sites/all/modules/contrib/cache_backport/cache.inc';
//\$conf['cache_backends'] = array('sites/all/modules/contrib/apc/drupal_apc_cache.inc');
//\$conf['cache_default_class'] = 'DrupalAPCCache';
//\$conf['page_cache_without_database'] = TRUE;
//\$conf['page_cache_invoke_hooks'] = FALSE;


\$drupal_db = array(
    'type' => 'mysqli',
    'server' => '$host',
    'name' => '$database',
    'user' => '$user',
    'pass' => '$password',
    'prefix' => '',
);

\$db_url = \$drupal_db['type'] . '://' . \$drupal_db['user'] . ':' . \$drupal_db['pass'] . '@' . \$drupal_db['server'] . '/' . \$drupal_db['name'];
\$db_prefix = \$drupal_db['prefix'];

include_once(DRUPAL_ROOT . '/sites/default/bootstrap.inc.php');

EOF
chmod 0644 $config_file_path

juju-log "Enabling Nginx site: $hostname"

chown -R www-data.www-data $drupal_install_path

if [ ! -f /etc/cron.daily/drupal-backup ]; then
  juju-log "Put the backup process in place"
  rsync -az files/drupal-backup /etc/cron.daily/
  chmod 0755 /etc/cron.daily/drupal-backup
fi

sed -i -e "s@DB_HOST=\".*\"@DB_HOST=\"$host\"@" \
    -e "s@DB_USER=\".*\"@DB_USER=\"$user\"@" \
    -e "s@DB_PASS=\".*\"@DB_PASS=\"$password\"@" \
    -e "s@DB_NAME=\".*\"@DB_NAME=\"$database\"@" \
    /etc/cron.daily/drupal-backup

# Restart nginx
juju-log "Restarting nginx service"
service nginx restart

# Make it publicly visible, once the wordpress service is exposed
open-port 80/tcp
open-port 8080/tcp
