#!/bin/bash

add-apt-repository ppa:charmers/charm-helpers

apt-get update && apt-get -y upgrade
apt-get -y install mysql-client pwgen nginx php5 php5-fpm php-apc mailutils php-mail sysstat php5-mysql php5-mcrypt charm-helper-sh s3cmd php5-curl rsync

rm -f /etc/cron.d/php5
mv files/php/php_conf.d_apc.ini /etc/php5/conf.d/

mkdir -p /mnt/tmp
chmod 1777 /mnt/tmp

rm -f /etc/nginx/sites-enabled/*
rm -f /etc/nginx/conf.d/*

rm -f /etc/nginx/nginx.conf
install -o root -g root -m 0644 files/nginx/etc_nginx_nginx.conf /etc/nginx/nginx.conf

rm -f /etc/nginx/sites-available/omgubuntu.co.uk
install -o root -g root -m 0644 files/nginx/etc_nginx_sites-enabled_omgubuntu.co.uk /etc/nginx/sites-available/omgubuntu.co.uk
ln -sf ../sites-available/omgubuntu.co.uk /etc/nginx/sites-enabled/omgubuntu.co.uk

rm -f /etc/nginx/sites-available/admin.omgubuntu.co.uk
install -o root -g root -m 0644 files/nginx/etc_nginx_sites-enabled_admin.omgubuntu.co.uk /etc/nginx/sites-available/admin.omgubuntu.co.uk
ln -sf ../sites-available/admin.omgubuntu.co.uk /etc/nginx/sites-enabled/admin.omgubuntu.co.uk

rm -f /etc/nginx/sites-available/loadbalancer
install -o root -g root -m 0644 files/nginx/etc_nginx_sites-enabled_loadbalancer /etc/nginx/sites-available/loadbalancer
ln -sf ../sites-available/loadbalancer /etc/nginx/sites-enabled/loadbalancer

rm -f /etc/php5/fpm/pool.d/*
install -o root -g root -m 0644 files/php/php5-fpm_pool.d_www.conf /etc/php5/fpm/pool.d/www.conf

rsync -avz /var/lib/nginx /mnt/ && rm -rf /var/lib/nginx && ln -s /mnt/nginx /var/lib/

service php5-fpm restart
service nginx restart

juju-log "So, environment is setup. We'll wait for some hooks to fire off before we get all crazy"
