#!/bin/bash

drupal_install_path="/var/www/drupal"

if [ -d $drupal_install_path ]; then
  juju-log "Upgrading Custom Drupal Files Themes, Modules, Libraries, etc"
  rsync -az drupal/ $drupal_install_path
  chown -R www-data.www-data $drupal_install_path
fi
